# Generated by Django 5.0.1 on 2024-01-27 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('DateOfBirth', models.DateField()),
                ('EnrollmentDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('HireDate', models.DateField()),
                ('Department', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('GradeID', models.AutoField(primary_key=True, serialize=False)),
                ('Grade', models.FloatField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_info.courses')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_info.students')),
            ],
        ),
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('DateAttended', models.DateField()),
                ('Status', models.CharField(max_length=200)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_info.students')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('EnrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DateEnrolled', models.DateField()),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_info.students')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_info.teachers')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='TeacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_info.teachers'),
        ),
    ]
